/*
 * Copyright (C) 2021 badi_
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package videorental;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.Date;
import java.sql.ResultSet;
import java.sql.Types;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author badi_
 */
public class CrewInfo extends javax.swing.JFrame {

    /**
     * Creates new form CrewInfo
     */
    public CrewInfo(DBManager DB, int crewID) {
        this.DB = DB;
        this.crewID = crewID;
        imageStream = null;

        initComponents();

        if (crewID != 0) {
            setTitle("Edit Cast/Crew");

            String sql = "SELECT Firstname, Lastname, DOB, Bio, Photo FROM Crew WHERE crewID = ?;";
            ArrayList<Object> data = new ArrayList<>();
            data.add(crewID);

            DB.connect();
            ResultSet result = DB.makeQuery(sql, data);
            DB.close();

            try {
                if (result.next()) {
                    jTextFieldFirstname.setText(result.getString(1));

                    String lastname = result.getString(2);
                    if (lastname != null) {
                        jTextFieldLastname.setText(lastname);
                    }

                    Date dob = result.getDate(3);
                    if (dob != null) {
                        jTextFieldDOB.setText(dob.toString());
                    }

                    String bio = result.getString(4);
                    if (bio != null) {
                        jTextAreaBio.setText(bio);
                    }

                    byte[] pic = result.getBytes(5);
                    if (pic != null) {
                        ImageIcon image = new ImageIcon(pic);
                        jLabelImage.setIcon(image);
                        jLabelImage.setText("Image loaded from database");
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Error reading info", "Read error", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
                closeWindow();
            }
        }
    }

    private void closeWindow() {
        WindowEvent closingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabelFirstname = new javax.swing.JLabel();
        jLabelLastname = new javax.swing.JLabel();
        jLabelDOB = new javax.swing.JLabel();
        jLabelBio = new javax.swing.JLabel();
        jTextFieldFirstname = new javax.swing.JTextField();
        jTextFieldLastname = new javax.swing.JTextField();
        jTextFieldDOB = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBio = new javax.swing.JTextArea();
        jButtonAddPhoto = new javax.swing.JButton();
        jLabelImage = new javax.swing.JLabel();
        jButtonCancel = new javax.swing.JButton();
        jButtonSubmit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Cast/Crew");
        setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabelFirstname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelFirstname.setText("<html>First Name<small><sup>*</sup></small>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabelFirstname, gridBagConstraints);

        jLabelLastname.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelLastname.setText("Last Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabelLastname, gridBagConstraints);

        jLabelDOB.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelDOB.setText("Date of Birth");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabelDOB, gridBagConstraints);

        jLabelBio.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelBio.setText("Biography");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanel1.add(jLabelBio, gridBagConstraints);

        jTextFieldFirstname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldFirstname.setMinimumSize(new java.awt.Dimension(140, 22));
        jTextFieldFirstname.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel1.add(jTextFieldFirstname, gridBagConstraints);

        jTextFieldLastname.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldLastname.setMinimumSize(new java.awt.Dimension(140, 22));
        jTextFieldLastname.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel1.add(jTextFieldLastname, gridBagConstraints);

        jTextFieldDOB.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldDOB.setMinimumSize(new java.awt.Dimension(140, 22));
        jTextFieldDOB.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 0, 0);
        jPanel1.add(jTextFieldDOB, gridBagConstraints);

        jTextAreaBio.setColumns(20);
        jTextAreaBio.setLineWrap(true);
        jTextAreaBio.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBio);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 5, 10, 0);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        jButtonAddPhoto.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonAddPhoto.setText("Change Photo");
        jButtonAddPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPhotoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        jPanel1.add(jButtonAddPhoto, gridBagConstraints);

        jLabelImage.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabelImage.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelImage.setText("No Photo Selected");
        jLabelImage.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabelImage.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabelImage.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelImage.setMaximumSize(new java.awt.Dimension(500, 800));
        jLabelImage.setVerticalTextPosition(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabelImage, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 100;
        gridBagConstraints.ipady = 100;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(jPanel1, gridBagConstraints);

        jButtonCancel.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonCancel.setText("Cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonCancel, gridBagConstraints);

        jButtonSubmit.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonSubmit.setText("Submit");
        jButtonSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubmitActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonSubmit, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPhotoActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Image files", "jpg", "gif", "png");
        chooser.addChoosableFileFilter(filter);
        chooser.setFileFilter(filter);
        chooser.setMultiSelectionEnabled(false);

        int choice = chooser.showOpenDialog(this);

        if (choice == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();

            try {
                jLabelImage.setIcon(new ImageIcon(file.getPath()));
                imageStream = new FileInputStream(file);

                jLabelImage.setText(file.getName());
            } catch (Exception e) {
                jLabelImage.setText("Error: Image failed to load");
            }
        }

    }//GEN-LAST:event_jButtonAddPhotoActionPerformed

    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        closeWindow();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jButtonSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubmitActionPerformed
        jLabelFirstname.setForeground(Color.black);
        jLabelDOB.setForeground(Color.black);

        String firstname = jTextFieldFirstname.getText();
        String lastname = jTextFieldLastname.getText();
        String dobText = jTextFieldDOB.getText();
        String bio = jTextAreaBio.getText();

        //make sure that first name was entered. Last name is not required due to many artists only using a single name
        if (firstname.isEmpty()) {
            jTextFieldFirstname.setForeground(Color.red);
            return;
        }
        //make sure that date format is correct
        if (!dobText.isEmpty() && !dobText.matches("\\d\\d\\d\\d-\\d\\d-\\d\\d")) {
            jTextFieldDOB.setForeground(Color.red);
            return;
        }

        String sql;
        if (crewID > 0) {
            sql = "UPDATE Crew SET Firstname = ?, Lastname = ?, DOB = ?, Bio = ?";
            if (imageStream != null) {
                sql += ", Photo = ?";
            }
            sql += " WHERE CrewID = ?;";
            
        } else {
            sql = "INSERT INTO Crew (CrewID, Firstname, Lastname, DOB, Bio, Photo) VALUES (null, ?, ?, ?, ?, ?);";
        }
        ArrayList<Object> data = new ArrayList<>();

        //create array for data and fill it with values
        data.add(firstname);
        if (lastname.isEmpty()) {
            data.add(new NullParameter(Types.VARCHAR));
        } else {
            data.add(lastname);
        }
        if (dobText.isEmpty()) {
            data.add(new NullParameter(Types.DATE));
        } else {
            Date dob = Utils.getDate(dobText);
            data.add(dob);
        }
        if (bio.isEmpty()) {
            data.add(new NullParameter(Types.VARCHAR));
        } else {
            data.add(bio);
        }
        if (imageStream == null && crewID == 0) {
            data.add(new NullParameter(Types.BLOB));
        } else if (imageStream != null) {
            data.add(imageStream);
        }
        if (crewID > 0) {
            data.add(Integer.valueOf(crewID));
        }

        DB.connect();
        DB.makeQuery(sql, data);
        DB.close();

        closeWindow();
    }//GEN-LAST:event_jButtonSubmitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrewInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrewInfo(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddPhoto;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSubmit;
    private javax.swing.JLabel jLabelBio;
    private javax.swing.JLabel jLabelDOB;
    private javax.swing.JLabel jLabelFirstname;
    private javax.swing.JLabel jLabelImage;
    private javax.swing.JLabel jLabelLastname;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaBio;
    private javax.swing.JTextField jTextFieldDOB;
    private javax.swing.JTextField jTextFieldFirstname;
    private javax.swing.JTextField jTextFieldLastname;
    // End of variables declaration//GEN-END:variables
    private DBManager DB;
    private int crewID;
    private FileInputStream imageStream;
}
