/*
 * Copyright (C) 2021 badi_
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package videorental;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.ArrayList;

/**
 *
 * @author Badi Moore
 * badi_moore@hotmail.com
 */
public class EditKeywords extends javax.swing.JFrame {

    /**
     * Creates new form EditCrewRoles
     */
    public EditKeywords(DBManager DB) {
        this.DB = DB;
        
        initComponents();
       
        DB.connect();
        loadKeywords();
        DB.close(); 
    }
    
    private void loadKeywords() {
        String sql = "SELECT RatingkeywordID, Keyword FROM Ratingkeyword;";
        ResultSet result = DB.makeQuery(sql);
        Utils.populateTable(jTableKeywords, result);
    }
    
    private void closeWindow() {
        WindowEvent closingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMain = new javax.swing.JPanel();
        jTextFieldNewKeyword = new javax.swing.JTextField();
        jLabelNewKeyword = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableKeywords = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonRemove = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Age Rating Keywords");
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelMain.setBackground(new java.awt.Color(250, 250, 250));
        jPanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMain.setLayout(new java.awt.GridBagLayout());

        jTextFieldNewKeyword.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextFieldNewKeyword.setMinimumSize(new java.awt.Dimension(140, 22));
        jTextFieldNewKeyword.setPreferredSize(new java.awt.Dimension(140, 22));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 5, 0, 0);
        jPanelMain.add(jTextFieldNewKeyword, gridBagConstraints);

        jLabelNewKeyword.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelNewKeyword.setText("New Keyword");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelMain.add(jLabelNewKeyword, gridBagConstraints);

        jTableKeywords.setAutoCreateRowSorter(true);
        jTableKeywords.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTableKeywords.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Keyword"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableKeywords.setFillsViewportHeight(true);
        jTableKeywords.setRowHeight(20);
        jTableKeywords.setShowHorizontalLines(false);
        jTableKeywords.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTableKeywords);
        if (jTableKeywords.getColumnModel().getColumnCount() > 0) {
            jTableKeywords.getColumnModel().getColumn(0).setMinWidth(0);
            jTableKeywords.getColumnModel().getColumn(0).setPreferredWidth(0);
            jTableKeywords.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        jPanelMain.add(jScrollPane1, gridBagConstraints);

        jButtonAdd.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonAdd.setText("Add Keyword");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(8, 10, 0, 0);
        jPanelMain.add(jButtonAdd, gridBagConstraints);

        jButtonRemove.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonRemove.setText("Remove Keyword");
        jButtonRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 10, 10);
        jPanelMain.add(jButtonRemove, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(jPanelMain, gridBagConstraints);

        jButtonClose.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonClose, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        jLabelNewKeyword.setForeground(Color.black);
        String newKeyword = jTextFieldNewKeyword.getText();
        
        if (newKeyword.isBlank()) {
            jLabelNewKeyword.setForeground(Color.red);
            return;
        }
        
        String sql = "INSERT INTO Ratingkeyword (RatingkeywordID, Keyword, Icon) VALUES (null, ?, null);";
        ArrayList<Object> data = new ArrayList<>();
        
        data.add(newKeyword);
        
        DB.connect();
        DB.makeQuery(sql, data);
        loadKeywords();
        DB.close();
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        closeWindow();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveActionPerformed
        int selectedRow = jTableKeywords.getSelectedRow();
        if (selectedRow < 0) {
            return;
        }
        Integer selectedID = (Integer) Utils.getSelectedCellContent(selectedRow, 0, jTableKeywords);
        String sql = "DELETE FROM Ratingkeyword WHERE RatingkeywordID=?;";
        
        ArrayList<Object> data = new ArrayList<>();
        data.add(selectedID);
        
        DB.connect();
        DB.makeQuery(sql, data);
        loadKeywords();
        DB.close();
    }//GEN-LAST:event_jButtonRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditKeywords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditKeywords(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonRemove;
    private javax.swing.JLabel jLabelNewKeyword;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableKeywords;
    private javax.swing.JTextField jTextFieldNewKeyword;
    // End of variables declaration//GEN-END:variables
    private DBManager DB;

}
