/*
 * Copyright (C) 2021 badi_
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package videorental;

import java.awt.Color;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.util.ArrayList;

/**
 *
 * @author Badi Moore badi_moore@hotmail.com
 */
public class ViewReview extends javax.swing.JFrame {

    /**
     * Creates new form EditCrewRoles
     */
    public ViewReview(DBManager DB, Integer reviewID) {
        this.DB = DB;

        initComponents();

        String sql = "SELECT CONCAT(Customer.Firstname, ' ', Customer.Lastname), Customer.Displayname, Review.Stars, Review.Time, Review.Content FROM Review"
                + " INNER JOIN Customer USING(CustomerID)"
                + " WHERE ReviewID = ?";
        ArrayList<Object> data = new ArrayList<>();
        data.add(reviewID);

        DB.connect();
        ResultSet result = DB.makeQuery(sql, data);
        DB.close();

        try {
            if (result.next()) {
                jLabelResultName.setText(result.getString(1));
                jLabelResultNick.setText(result.getString(2));
                jLabelResultStars.setText("<html>" + Utils.starText(result.getFloat(3), false));
                jLabelResultDatetime.setText(result.getTimestamp(4).toString());
                String reviewText = result.getString(5);
                if (reviewText != null) {
                    jTextAreaReview.setText(reviewText);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void closeWindow() {
        WindowEvent closingEvent = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closingEvent);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanelMain = new javax.swing.JPanel();
        jLabelReviewer = new javax.swing.JLabel();
        jLabelDisplayName = new javax.swing.JLabel();
        jLabelDisplayDateTime = new javax.swing.JLabel();
        jLabelStars = new javax.swing.JLabel();
        jLabelResultName = new javax.swing.JLabel();
        jLabelResultNick = new javax.swing.JLabel();
        jLabelResultStars = new javax.swing.JLabel();
        jLabelResultDatetime = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaReview = new javax.swing.JTextArea();
        jButtonClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("View Review");
        setMinimumSize(new java.awt.Dimension(400, 500));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanelMain.setBackground(new java.awt.Color(250, 250, 250));
        jPanelMain.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelMain.setMinimumSize(new java.awt.Dimension(500, 300));
        jPanelMain.setPreferredSize(new java.awt.Dimension(600, 400));
        jPanelMain.setLayout(new java.awt.GridBagLayout());

        jLabelReviewer.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelReviewer.setText("Reviewer");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelMain.add(jLabelReviewer, gridBagConstraints);

        jLabelDisplayName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelDisplayName.setText("Display Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelMain.add(jLabelDisplayName, gridBagConstraints);

        jLabelDisplayDateTime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelDisplayDateTime.setText("Date/Time");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanelMain.add(jLabelDisplayDateTime, gridBagConstraints);

        jLabelStars.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelStars.setText("Stars");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelMain.add(jLabelStars, gridBagConstraints);

        jLabelResultName.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelResultName.setForeground(new java.awt.Color(90, 90, 90));
        jLabelResultName.setText("Name");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelMain.add(jLabelResultName, gridBagConstraints);

        jLabelResultNick.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelResultNick.setForeground(new java.awt.Color(90, 90, 90));
        jLabelResultNick.setText("Nick");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelMain.add(jLabelResultNick, gridBagConstraints);

        jLabelResultStars.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelResultStars.setForeground(new java.awt.Color(250, 164, 26));
        jLabelResultStars.setText("***");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 0);
        jPanelMain.add(jLabelResultStars, gridBagConstraints);

        jLabelResultDatetime.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jLabelResultDatetime.setForeground(new java.awt.Color(90, 90, 90));
        jLabelResultDatetime.setText("Datetime");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        jPanelMain.add(jLabelResultDatetime, gridBagConstraints);

        jTextAreaReview.setEditable(false);
        jTextAreaReview.setColumns(20);
        jTextAreaReview.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jTextAreaReview.setLineWrap(true);
        jTextAreaReview.setRows(5);
        jTextAreaReview.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextAreaReview);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 10, 10);
        jPanelMain.add(jScrollPane1, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 0, 10);
        getContentPane().add(jPanelMain, gridBagConstraints);

        jButtonClose.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jButtonClose.setText("Close");
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jButtonClose, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        closeWindow();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Metal look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewReview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewReview(null, 0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClose;
    private javax.swing.JLabel jLabelDisplayDateTime;
    private javax.swing.JLabel jLabelDisplayName;
    private javax.swing.JLabel jLabelResultDatetime;
    private javax.swing.JLabel jLabelResultName;
    private javax.swing.JLabel jLabelResultNick;
    private javax.swing.JLabel jLabelResultStars;
    private javax.swing.JLabel jLabelReviewer;
    private javax.swing.JLabel jLabelStars;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaReview;
    // End of variables declaration//GEN-END:variables
    private DBManager DB;

}
